language: c
dist: trusty
addons:
  apt:
    packages:
      - python-gobject
install:
  - wget https://downloads.sourceforge.net/project/zero-install/0install/2.12.1/0install-linux-x86_64-2.12.1.tar.bz2;
    tar xf 0install-linux-x86_64-2.12.1.tar.bz2;
    ( cd 0install-linux-x86_64-2.12.1 && ./install.sh home )
  - 0install -c add 0compile http://0install.net/2006/interfaces/0compile.xml
  - 0install -c add 0publish http://0install.net/2006/interfaces/0publish
script:
  - git submodule update --remote
  - pwd;
    if [ -d 0compile.version/ ]; then
      version=$( (cd 0compile.version && git describe --tags --dirty --always | sed "s/^[^0-9]*//") );
    elif [ -x 0compile.version ]; then
      version=$(./0compile.version);
    elif [ -e 0compile.version ]; then
      version=$(cat 0compile.version);
    else
      version=$(git describe --tags --dirty --always | sed "s/^[^0-9]*//");
    fi
  - if [ -n "$version" ]; then
      feed=$(python3 -c 'import configparser;c=configparser.ConfigParser();c.read("0compile.properties");print(c["compile"]["interface"])');
      0publish --set-version=$version --select-version=0 $feed;
    fi
  - if [ -x 0compile.sh ]; then
      ./0compile.sh;
    else
      feed=$(python3 -c 'import configparser;c=configparser.ConfigParser();c.read("0compile.properties");print(c["compile"]["interface"])');
      0compile build;
      0compile publish --target-feed=${feed}_implem.xml .;
      0publish -a ${feed}_implem.xml $feed;
    fi
  - eval "$(ssh-agent -s)"
  - echo "$GIT_DEPLOY_KEY" | base64 -d | ssh-add -
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - git config --global url.ssh://git@github.com/.insteadOf http://github.com/
  - remote_url="$(git config remote.origin.url)"
  - if ! git clone -b gh-pages $remote_url gh-pages; then
      set -e;
      git clone --no-checkout $remote_url gh-pages;
      ( cd gh-pages;
        git checkout --orphan gh-pages
      )
    fi
  - ls -l
