language: c
dist: trusty
addons:
  apt:
    packages:
      - python-gobject
install:
  - wget https://downloads.sourceforge.net/project/zero-install/0install/2.12.1/0install-linux-x86_64-2.12.1.tar.bz2;
    tar xf 0install-linux-x86_64-2.12.1.tar.bz2;
    ( cd 0install-linux-x86_64-2.12.1 && ./install.sh home )
  - 0install -c add 0compile http://0install.net/2006/interfaces/0compile.xml
  - 0install -c add 0publish http://0install.net/2006/interfaces/0publish
script:
  - gpg-agent -s -vv --allow-preset-passphrase --no-detach
  - eval "$(ssh-agent -s)"
  - echo "$GPG_PASSPHRASE" | python2 -c 'import sys, binascii; sys.stdout.write(binascii.b2a_hex(sys.stdin.read().strip()))' | xargs printf "PRESET_PASSPHRASE $GPG_KEY_ID -1 %s\n" | gpg-connect-agent
  - gpg --batch --import "$GPG_KEY_ID.skey"
  - unset GPG_PASSPHRASE
  - git submodule update --remote
  - git config --global url.ssh://git@github.com/.insteadOf http://github.com/
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - cat ~/.gitconfig
  - feed=$(python3 -c 'import configparser;c=configparser.ConfigParser();c.read("0compile.properties");print(c["compile"]["interface"])');
  - echo "$GIT_DEPLOY_KEY" | base64 -d | ssh-add -
  - remote_url="$(git config remote.origin.url)"
  - if ! git clone -b gh-pages $remote_url gh-pages; then
      set -e;
      git clone --no-checkout $remote_url gh-pages;
      ( cd gh-pages;
        git checkout --orphan gh-pages;
        git rm -rf .
      )
    fi
  - if ! [ -e "gh-pages/$feed" ]; then cp "$feed" "gh-pages/$feed"; fi
  - if [ -d 0compile.version/ ]; then
      version=$( (cd 0compile.version && git describe --tags --dirty --always | sed "s/^[^0-9]*//") );
    elif [ -x 0compile.version ]; then
      version=$(./0compile.version);
    elif [ -e 0compile.version ]; then
      version=$(cat 0compile.version);
    else
      version=$(git describe --tags --dirty --always | sed "s/^[^0-9]*//");
    fi
  - if [ -n "$version" ]; then
      0publish --set-version=$version --select-version=0 $feed;
    fi
  - if [ -x 0compile.sh ]; then
      eval "$(./0compile.sh)";
      archive="$(sed -n -e 's/.*<archive.*href=["'"'"']\([^"'"'"']*\)["'"'"'].*/\1/p' "$new_feed")";
    else
      0compile build;
      pub="$(0compile publish .)";
      echo "$pub";
      archive="$(echo "$pub" | sed -n '2 p')";
      new_feed="$(echo "$pub" | sed -n 's/^\$ 0launch //p')";
    fi
  - cp "$archive" gh-pages
  - cat gh-pages/$feed >$feed.old
  - sed -i '/<implementation .*version=["'"'"']'"$version"'["'"'"']/,/<\/implementation>/ d' "gh-pages/$feed"
  - 0publish -a "${new_feed}" "gh-pages/$feed"
  - 0publish --xmlsign -k $GPG_KEY_ID "gh-pages/$feed"
  - gpg --armor --output gh-pages/$GPG_KEY_ID.key --export $GPG_KEY_ID
  - cat gh-pages/$feed >$feed.new
  - diff -u $feed.old $feed.new || true
  - (cd gh-pages && git add "$(basename "$archive")")
  - (cd gh-pages && git add "$feed" "$GPG_KEY_ID.key")
  - (cd gh-pages && git commit -m "Release" || true)
after_success:
  - (cd gh-pages && git push origin gh-pages)
